### ISSUE TITLE
Running in python3

### ISSUE THREAD

**Issue by flopezlira** [tansey/rl-tictactoe#3]
Hello Wesley.

Thanks for this great program.

I tried to run the program in python3 and I found these messages:

1. The first has to do with the print function, which is easily solved
2. On line 91 "list indices must be integers or slices, not float". I changed lines 88-89 to generate int values but I don't know if that is correct
3. Line 305: "a bytes-like object is required, not 'str'". It is because you open the file for writing binaries. I changed line 303 to "w" only but I don't know if it's the right solution.

Thanks again

**Comment by tansey** [comment]
Yeah, I believe this is python 2 only at the moment. Not super high on my priority queue to make it python 3 compatible. Happy to accept a pull request if you do though!
